### ISSUE TITLE
Right Keypress not working in the input

### ISSUE THREAD

**Issue by happymango7** [sslotsky/react-tag-box#8]
In order to edit text while typing, tried to use left and right key.
Left key works but right key. 
Thanks,

**Comment by sslotsky** [comment]
Indeed, thanks for spotting that. Probably related to this:

https://github.com/sslotsky/react-tag-box/blob/master/src/TagManager.js#L8

It's supposed to prevent default behavior for keys that are supposed to execute these actions. It's not immediately clear why the left key behaves differently from the right, but we might want to allow default behavior for those keys instead of assuming that we should treat them all the same.

Please feel free to investigate and submit a PR, I may not get time to work on this right away.

**Comment by ogerfaber** [comment]
Do you have any update on this ? I'm not enough confident with your codebase to make a PR, event if it seems to be a little fix. Do you think you can fix it ?

**Comment by sslotsky** [comment]
My recollection is that I spent some time looking for a straightforward/easy fix and did not find one. I'd like to be of more help but I have not been maintaining my OSS projects and I don't see that changing any time soon. I'm sorry that this is causing issues for you.

**Comment by ogerfaber** [comment]
Thanks for you reponse, I completly understand
